guizhou-app/package-lock.json, guizhou-app/package.json, guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.scss, guizhou-app/src/app/app-deploy/app-deploy.component.spec.ts, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.html, guizhou-app/src/app/app-release/app-release.component.scss, guizhou-app/src/app/app-release/app-release.component.spec.ts, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/app-routing.module.ts, guizhou-app/src/app/app-store/app-store.component.html, guizhou-app/src/app/app.module.ts, guizhou-app/src/app/component-test/component-test.component.html, guizhou-app/src/app/component-test/component-test.component.ts, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.html, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.scss, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.ts, guizhou-app/src/app/dynamic-form/models/field-config.interface.ts, guizhou-app/src/app/repository-detail/repository-detail.component.html, guizhou-app/tsconfig.json
=> 发布应用+应用部署(初始化)

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/app.module.ts, guizhou-app/src/app/component-test/component-test.component.html, guizhou-app/src/app/component-test/component-test.component.ts, guizhou-app/src/app/container-instance/container-instance.component.html, guizhou-app/src/app/container-instance/container-instance.component.scss, guizhou-app/src/app/container-instance/container-instance.component.spec.ts, guizhou-app/src/app/container-instance/container-instance.component.ts, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.html, guizhou-app/src/app/dynamic-form/components/form-radio/form-radio.component.html, guizhou-app/src/app/dynamic-form/components/form-radio/form-radio.component.spec.ts, guizhou-app/src/app/dynamic-form/components/form-radio/form-radio.component.ts, guizhou-app/src/app/dynamic-form/dynamic-form.module.ts, guizhou-app/src/app/repository-detail/repository-detail.component.ts, guizhou-app/src/app/service-detail/service-detail.component.ts, guizhou-app/src/app/shared/random-user.service.ts, guizhou-app/src/app/shared/services.service.ts
=> 应用部署（api还没调好）

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.scss, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.html, guizhou-app/src/app/app-release/app-release.component.scss, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/app.component.ts, guizhou-app/src/app/container-instance/container-instance.component.html, guizhou-app/src/app/container-instance/container-instance.component.ts, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.html, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.ts, guizhou-app/src/app/dynamic-form/models/field-config.interface.ts
=> 应用部署、应用发布优化代码

guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.html, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.ts, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html, guizhou-app/src/app/dynamic-form/containers/dynamic-form/dynamic-form.component.ts, guizhou-app/src/environments/environment.ts
=> 发布应用，接口完全调通

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.html, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.ts, guizhou-app/src/app/dynamic-form/containers/dynamic-form/dynamic-form.component.ts, guizhou-app/src/app/dynamic-form/models/field-config.interface.ts, guizhou-app/src/environments/environment.ts
=> 应用部署页面，根据api动态渲染页面

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.html, guizhou-app/src/app/app-release/app-release.component.scss, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/app-routing.module.ts, guizhou-app/src/app/app.module.ts, guizhou-app/src/app/dynamic-form/components/form-button/form-button.component.html, guizhou-app/src/app/dynamic-form/containers/dynamic-form/dynamic-form.component.scss, guizhou-app/src/app/dynamic-form/models/field-config.interface.ts, guizhou-app/src/app/service-detail/service-detail.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.scss, guizhou-app/src/app/service-subscribe/service-subscribe.component.spec.ts, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts
1、应用发布、应用部署、服务订购ui优化
2、应用发布、应用部署、服务订购api调试
=> 页面优化+api调试

guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.html, guizhou-app/src/app/app-release/app-release.component.scss, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/app-routing.module.ts, guizhou-app/src/app/component-test/component-test.component.html, guizhou-app/src/app/component-test/component-test.component.scss, guizhou-app/src/app/component-test/component-test.component.ts, guizhou-app/src/app/repository-detail/repository-detail.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts, guizhou-app/src/styles.css
应用部署 + 服务订购api调通
1、应用部署，正常流程下，api可以跑通，主机标签选择一个没问题，多选由于集群资源不足会报错
2、服务订购流程如上
3、后续会针对资源不足时，做统一的异常处理
=> 应用部署 + 服务订购api调通

guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-routing.module.ts, guizhou-app/src/app/app.module.ts, guizhou-app/src/app/build-image/build-image.component.html, guizhou-app/src/app/build-image/build-image.component.scss, guizhou-app/src/app/build-image/build-image.component.spec.ts, guizhou-app/src/app/build-image/build-image.component.ts, guizhou-app/src/app/mirror-store/mirror-store.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts
=> 应用部署、服务订购bug修复 + 镜像上传部分版

guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/build-image/build-image.component.html, guizhou-app/src/app/build-image/build-image.component.ts, guizhou-app/src/app/service-subscribe/service-subscribe.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts
1、镜像上传页面+api调试
2、应用发布、应用部署、服务订购优化“返回”和“上一步”等逻辑
3、服务订购请求灵雀云api时，页面增加loading状态
=> 镜像上传页面+api调试、应用、服务页面调整

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.scss, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.html, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/app-routing.module.ts, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.ts, guizhou-app/src/app/dynamic-form/containers/dynamic-form/dynamic-form.component.ts, guizhou-app/src/app/service-detail/service-detail.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.scss, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts
zookeeper、redis、kafka高级配置，增加动态配置
=> 服务订购、应用部署api调试

guizhou-app/src/app/app-release/app-release.component.html, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/service-subscribe/service-subscribe.component.html
1、图片上传限定最多只能上传一张图片
2、修复拖拽图片上传时的跨域问题
3、删掉应用发布刚进来时的弹出框蒙层
=> 发布应用页面Bug修复

guizhou-app/src/app/component-test/component-test.component.ts, guizhou-app/src/app/util/error-interceptor/error-interceptor.component.ts, guizhou-app/src/assets/i18n/en.json, guizhou-app/src/assets/i18n/zh.json
1、全局错误通知组件封装基本完成
2、国际化翻译服务基本引入项目完成
=> 全局错误通知+国际化翻译

guizhou-app/package-lock.json, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/app.module.ts, guizhou-app/src/app/build-image/build-image.component.ts, guizhou-app/src/app/component-test/component-test.component.html, guizhou-app/src/app/component-test/component-test.component.ts, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.html, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.ts, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.ts, guizhou-app/src/app/dynamic-form/containers/dynamic-form/dynamic-form.component.html, guizhou-app/src/app/dynamic-form/dynamic-form.module.ts, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts, guizhou-app/src/app/util/error-interceptor/error-interceptor.component.ts, guizhou-app/src/app/util/reg-pattern/reg-name.directive.spec.ts, guizhou-app/src/app/util/reg-pattern/reg-name.directive.ts, guizhou-app/src/assets/i18n/en.json, guizhou-app/src/assets/i18n/zh.json
1、项目引入ngx-translate，可以用作service、pipe等
2、完成了util/error-interceptor全局错误通知拦截器，并且引入了ngx-translate做国际化翻译
3、针对服务订购、发布应用、镜像上传、应用部署，根据灵雀云提供的Reg文档，做出相应的表单交单规则，并且增加错误通知国际化翻译文案
4、引入ng-zorro-antd nz-form提供的input error class，完全匹配原型的err class
=> 全局通知+国际化翻译+表单校验

guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/component-test/component-test.component.html, guizhou-app/src/app/component-test/component-test.component.ts, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.ts, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.ts, guizhou-app/src/app/dynamic-form/containers/dynamic-form/dynamic-form.component.ts, guizhou-app/src/app/dynamic-form/dynamic-form.module.ts, guizhou-app/src/app/dynamic-form/models/field-config.interface.ts, guizhou-app/src/app/dynamic-form/services/component-service.service.spec.ts, guizhou-app/src/app/dynamic-form/services/component-service.service.ts
1、应用发布删除enProd代码
2、动态表单组件，增加services层，用于表单子组件层级，对外进行通讯（50%）
=> 应用发布bug、表单组件扩展

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html
1、应用部署新增高级配置：服务类型、日志文件、环境变量
2、应用部署新增网络配置：网络模式、容器暴露端口、负载均衡器
=> 应用部署，高级配置+网络配置

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts, guizhou-app/src/environments/environment.ts
1、服务订购，新增集群选择，iptag获取数据从假值 =》 后台真实数据
2、应用部署，集群选择，mock数据 =》后台真实数据
=> 服务订购、应用部署增加集群

guizhou-app/src/app/opera-event/opera-event.component.ts, guizhou-app/src/app/opera-overview/opera-alert-base/opera-alert-base.component.css, guizhou-app/src/app/opera-overview/opera-alert-base/opera-alert-base.component.ts, guizhou-app/src/app/opera-overview/opera-alert-info/opera-alert-info.component.css, guizhou-app/src/app/opera-overview/opera-overview.component.html, guizhou-app/src/app/opera-overview/opera-overview.component.ts, guizhou-app/src/app/opera-overview/opera-resource/opera-resource.component.css, guizhou-app/src/app/opera-overview/opera-resource/opera-resource.component.html, guizhou-app/src/app/opera-overview/opera-view/opera-view.component.html, guizhou-app/src/app/opera-overview/opera-view/opera-view.component.ts
修改服务统计与应用统计的顺序  
运维模块-大数据部分（待联调）
增加可分配/可使用的title
修复主机/集群总数显示不对的方式
修改告警饼图的配色
=> 修改服务统计与应用统计的顺序

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.scss, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/component-test/component-test.component.html, guizhou-app/src/app/component-test/component-test.component.ts, guizhou-app/src/app/service-subscribe/service-subscribe.component.html, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts
1、增加zkList列表数据
2、等原型出来，基本配置增加负载均衡配置
3、等原型出来，应用部署lb更新
4、应用部署，负载均衡，更新lb-ports获取的api地址
=> dubbo服务订购 + 应用部署lb更新

guizhou-app/src/app/service-subscribe/service-subscribe.component.ts
=> 服务订购bugfix

guizhou-app/src/app/app-deploy/app-deploy.component.ts
=> 应用部署，负载均衡nginx

guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-overview-detail/app-overview-detail.component.html, guizhou-app/src/app/app-overview-detail/app-overview-detail.component.ts, guizhou-app/src/app/gray-deploy/gray-deploy.component.scss, guizhou-app/src/app/gray-deploy/gray-deploy.component.ts
1、应用部署 + 灰度部署，负载均衡器列表，新增http请求时，nginx数据加载
2、灰度详情，新增删除功能，删除之后重新刷新列表数据
3、灰度详情，正式升级modal内容修改
=> 灰度详情删除功能、详情bugfix

guizhou-app/src/app/shared/services.service.ts
=> 解决项目组为空的Bug

guizhou-app/src/app/build-image/build-image.component.ts
=> 镜像构建增加size字段

guizhou-app/src/app/app-instance-detail-detail/app-instance-detail-detail.component.ts, guizhou-app/src/app/app-logs/app-logs.component.ts, guizhou-app/src/app/app-monitor/app-monitor.component.ts, guizhou-app/src/app/app-nztable/app-nztable.component.ts, guizhou-app/src/app/app-overview-detail-detail/app-overview-detail-detail.component.ts, guizhou-app/src/app/app-overview-detail/app-overview-detail.component.ts, guizhou-app/src/app/app-overview/app-overview.component.ts, guizhou-app/src/app/app-store/app-store.component.ts, guizhou-app/src/app/configs/config-control/config-control.component.ts, guizhou-app/src/app/configs/config-detail/config-detail.component.ts, guizhou-app/src/app/mirror-store-list/mirror-store-list.component.ts, guizhou-app/src/app/opera-log/opera-log.component.ts, guizhou-app/src/app/repository-detail/repository-detail.component.ts, guizhou-app/src/app/service-detail/service-detail.component.ts, guizhou-app/src/app/service-instance-detail/service-instance-detail.component.ts, guizhou-app/src/app/service-instance/service-instance.component.ts, guizhou-app/src/app/service-list/service-list.component.ts, guizhou-app/src/app/shared/random-user.service.ts, guizhou-app/src/app/shared/services.service.ts
=> http => httpclient升级

guizhou-app/src/app/app-overview-detail/app-overview-detail.component.ts, guizhou-app/src/app/app-release/app-release.component.html, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/build-image/build-image.component.html, guizhou-app/src/app/build-image/build-image.component.ts, guizhou-app/src/app/component-test/component-test.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.ts, guizhou-app/src/app/repository-detail/repository-detail.component.css, guizhou-app/src/app/repository-detail/repository-detail.component.html, guizhou-app/src/app/repository-detail/repository-detail.component.ts
1、未部署任何应用，灰度部署按钮仍为可用状态
2、灰度部署第一步，获取potential-rules，如果长度为0，做处理
3、当应用中只有一个版本时，该版本上灰度部署为可用状态
=> 应用、镜像bugfix

guizhou-app/src/app/app-overview-detail/app-overview-detail.component.ts, guizhou-app/src/app/app-overview/app-overview.component.html, guizhou-app/src/app/app-overview/app-overview.component.ts, guizhou-app/src/app/app-release/app-release.component.html, guizhou-app/src/app/build-image-category/build-image-category.component.html, guizhou-app/src/app/build-image/build-image.component.html, guizhou-app/src/app/mirror-store-list/mirror-store-list.component.html, guizhou-app/src/app/repository-detail/repository-detail.component.html, guizhou-app/src/app/service-instance/service-instance.component.html, guizhou-app/src/app/service-instance/service-instance.component.ts
=> 灰度详情、应用/服务实例bugfix

.gitignore, guizhou-app/package-lock.json, guizhou-app/proxy.conf.json, guizhou-app/src/app/app-env-arg/app-env-arg.component.ts, guizhou-app/src/app/app-instance-detail-detail/app-config-file/app-config-file.component.ts, guizhou-app/src/app/app-instance-detail-detail/app-env-file/app-env-file.component.ts, guizhou-app/src/app/app-nztable/app-nztable.component.html, guizhou-app/src/app/app-overview-detail/app-overview-detail.component.html, guizhou-app/src/app/app-overview/app-overview.component.html, guizhou-app/src/app/app.component.html, guizhou-app/src/app/opera-event/opera-event.component.ts, guizhou-app/src/app/opera-overview/opera-alert-info/opera-alert-info.component.ts, guizhou-app/src/app/opera-overview/opera-overview.component.ts, guizhou-app/src/app/shared/services.service.ts
2. BDPAAS-579 灰度部署的实例，更新版本时，状态为更新状态时，也能点击更新
=> 1. BDPAAS-620 应用实例启动失败后，启动按钮应该可以点击启动，停止按钮不能点击

guizhou-app/src/app/gray-deploy/gray-deploy.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.ts
=> 灰度部署，多镜像页面优化 + 支持有状态服务

guizhou-app/src/app/service-list/service-list.component.ts
=> 解决首次点击服务目录，列表不刷新的问题

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.scss, guizhou-app/src/app/app-instance-detail-detail/app-config-file/app-config-file.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.scss
1、灰度部署，增加帮助提示，调整UI格式
2、应用部署，调整UI格式
3、添加配置文件文案调整
=> 应用部署、灰度部署优化

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-instance-detail-detail/app-env-file/app-env-file.component.ts, guizhou-app/src/app/app-instance-detail-detail/app-instance-detail-detail.component.html, guizhou-app/src/app/app-nztable/app-nztable.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.ts, guizhou-app/src/app/service-instance-detail/service-instance-detail.component.html
1、服务实例、应用实例error，点击详情报错，返回去出现重复值
2、应用部署+灰度部署，容器端口+协议增加hover提示
3、应用部署+灰度部署，第一步同名校验
=> 应用、服务bugfix

guizhou-app/src/app/service-subscribe/service-subscribe.component.ts
=> 服务启动，主机标签适配

guizhou-app/src/app/app-instance-detail-detail/app-config-file/app-config-file.component.scss, guizhou-app/src/app/app-overview-detail/app-overview-detail.component.html, guizhou-app/src/app/configs/config-detail/config-detail.component.scss, guizhou-app/src/app/gray-deploy/gray-deploy.component.html
1、ng zorro antd 0.6.x nz-select 默认有placeholder
2、配置文件去掉border和border radius
=> nz-select版本兼容

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/component-test/component-test.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.ts
=> 应用部署、灰度部署增加环境变量文件

guizhou-app/src/app/app-nztable/app-nztable.component.html, guizhou-app/src/app/app-nztable/app-nztable.component.ts, guizhou-app/src/app/app-overview-detail-detail/app-overview-detail-detail.component.html, guizhou-app/src/app/app-overview-detail-detail/app-overview-detail-detail.component.ts
=> 服务实例详情，增加环境变量展示

guizhou-app/src/app/app-overview-detail/app-overview-detail.component.html, guizhou-app/src/app/dynamic-form/components/form-select/form-select.component.html, guizhou-app/src/app/dynamic-form/models/field-config.interface.ts, guizhou-app/src/app/dynamic-form/models/field.interface.ts, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts
主机标签增加去重功能，api变动
主机标签下拉框后面增加提示信息
=> 主机标签增加去重功能，api变动

guizhou-app/src/app/app-instance-detail-detail/app-config-file/app-config-file.component.html, guizhou-app/src/app/app-instance-detail-detail/app-config-file/app-config-file.component.ts, guizhou-app/src/app/app-instance-detail-detail/app-env-file/app-env-file.component.ts, guizhou-app/src/app/opera-overview/opera-alert-info/opera-alert-info.component.ts
1. 修改删除应用实例环境变量时的传参
2. 配置文件级联效果改进
=> 修改删除应用实例环境变量时的传参&配置文件级联效果改进

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/dynamic-form/containers/dynamic-form/dynamic-form.component.ts, guizhou-app/src/app/gray-deploy/gray-deploy.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.ts
BDPAAS-988：应用部署，新增存储卷，未将上一次所添加的存储卷信息清空
BDPAAS-663：容器端口api地址更新，增加config配置
=> 应用部署bugfix

guizhou-app/src/app/app-deploy/app-deploy.component.html, guizhou-app/src/app/app-deploy/app-deploy.component.ts, guizhou-app/src/app/app-release/app-release.component.ts, guizhou-app/src/app/dynamic-form/components/form-input/form-input.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.html, guizhou-app/src/app/gray-deploy/gray-deploy.component.ts, guizhou-app/src/app/service-subscribe/service-subscribe.component.ts
BDPAAS-167  应用部署-高级配置-支持自定义接入点和执行命令
1、自定义接入点以及执行命令支持disabled切换
2、多高级配置，自定义接入点数据封装
3、input组件增加disabled参数配置
4、接入点支持镜像默认以及自定义两种格式
=> 自定义接入点和执行命令
